ARG PHP_BASE_IMAGE=scratch

FROM $PHP_BASE_IMAGE

LABEL maintainer="Yannick Vanhaeren"

SHELL ["/bin/bash", "-exo", "pipefail", "-c"]

ARG DEBIAN_FRONTEND=noninteractive
ARG PHP_VERSION

RUN apt update && apt install --assume-yes --no-install-recommends \
        imagemagick \
        ghostscript \
        php$PHP_VERSION-imagick && \
    apt clean && \
    rm --recursive /var/lib/apt/lists/* && \
    sed --in-place '/disable ghostscript format types/,+6d' /etc/ImageMagick-6/policy.xml
