name: "8.0"

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push php 8.0
        uses: docker/build-push-action@v6
        with:
          build-args:
            PHP_VERSION=8.0
          push: true
          tags: brabholdsa/php:8.0
      -
        name: Build and push php 8.0-imagick
        uses: docker/build-push-action@v6
        with:
          build-args: |
            PHP_BASE_IMAGE=brabholdsa/php:8.0
            PHP_VERSION=8.0
          file: Dockerfile.imagick
          push: true
          tags: brabholdsa/php:8.0-imagick
